spring:
  jackson:
    dateFormat: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    time-zone: UTC

eureka:
  instance:
    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
