server.port: ${PORT:8000}

spring:
  data.rest.maxPageSize: 10
  datasource:
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&preferredTestQuery=select now()
    username: root
    password: abcdEF123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa.show-sql: false
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
